import Nav from "@/components/Nav";
import "./globals.css";

export const metadata = {
  title: "Metabook",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-primary font-inter text-textcolor">
        <Nav />
        <div className="ml-[25%]">{children}</div>
      </body>
    </html>
  );
}
